### ISSUE TITLE
Console warnings and outstanding 2.0.0 version

### ISSUE THREAD

**Issue by mreishus** [compulim/react-scroll-to-bottom#37]
After installing the package from NPM, it works fine, but I get some errors in the console about unsupported lifecycle methods.

The 2.0.0 version which is on the master branch, but is not published to npm, gets rid of my warnings and works fine in my limited testing.  Is this going to be released on npm or is there some outstanding issues with it?

I see issue #29, and PR #36, but I'm not sure how it all fits together since the master branch seems to have already bumped react and fixed the warnings.

**Comment by RodolfoSilva** [comment]
@compulim @corinagum has any plan to publish the 2.0.0 version?

**Comment by compulim** [comment]
That's a lot of interests in this component.

I will make a project board and triage issues. I plan to work on some features over the next 2 months. Sorry, my real world job is busy recently because we are supporting entities who fight for coronavirus. 💪

Over the weekend, let me review my recent PRs to see if we should release `2.0.0` immediately or give it a bit more flushing.

Please do ping me over here if I am not responsive.

**Comment by mreishus** [comment]
2.0 was released a week and a half ago, and in my testing, it works fine and resolves the console warnings.  Thank you!
