### ISSUE TITLE
useObserveScrollPosition ,   can anyone please suggest an example of how to set it up withoout too much re render?

### ISSUE THREAD

**Issue by axeljeremy7** [compulim/react-scroll-to-bottom#70]

**Comment by compulim** [comment]
It depends on how your scenario of using streams of scroll positions. We don't suggest you to put the scroll position in `useState` because it will cause re-render. The best practices are similar to the `document.onscroll` event, https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event.

However, you can use the hook to filter out values. For example, when the scroll position is < `100px`, then your UI can light up, etc.

You can also implement a bookmark button by saving the latest scroll position using `useRef`, and the storing it `useState` when the user click on a button.

Hope it helps.
